name: coverage

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.0

      - name: Check out
        uses: actions/checkout@v3
        with:
          repository: golang/go
          path: go

      - name: coverage
        working-directory: ./go/src
        run: |
          GOROOT_BOOTSTRAP=/opt/hostedtoolcache/go/1.20.0/x64 ./all.bash
          ../bin/go test -cover ./... -coverprofile=cover.out
          ../bin/go tool cover -html=cover.out -o cover.html

      - name: copy
        run: |
          mkdir -p ./public
          cp ./go/src/cover.html ./public/

      - name: check
        run: ls -al ./public

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: public
